"""Pure graph-layer logic for the ilma Apache AGE integration.

This module contains no I/O. It transforms SQL result rows into a
:class:`GraphRebuildPlan` (vertices + edges + stats) and provides helpers for
escaping Cypher string literals and parsing AGE agtype wire-format values.

The actual Cypher execution lives in :mod:`ilma.storage.postgres_graph`.
Keeping this module pure means we can test the planning logic exhaustively
without spinning up Postgres.

Design contract:

- The graph is a **derived view** of the relational state in ``ilma.*``.
  Every edge can be regenerated by :func:`plan_graph_rebuild`.
- Edge properties record provenance so a manual override (e.g. user-curated
  edge) can be told apart from an auto-derived one.
- Substring matching for slug/skill-name references is **word-bounded** to
  avoid false positives like ``"science"`` matching the skill ``"ci"``.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any, Literal

VertexKind = Literal["Memory", "Wiki", "Skill"]
EdgeLabel = Literal[
    "SHARES_TAG",
    "CO_OCCURS",
    "REFERENCES_WIKI",
    "USES_SKILL",
]


# ---------------------------------------------------------------------------
# Cypher literal escape
# ---------------------------------------------------------------------------


def cypher_quote(value: Any) -> str:
    """Serialize a Python value as a Cypher literal.

    Cypher string literals use single quotes with single-quote-doubling for
    escape (SQL-style). Within a ``$$ ... $$`` block, single-quoted strings
    inside still need their inner quotes doubled; ``$`` itself is not special
    inside a string literal. Backslash is an escape character, so we must
    double backslashes too.

    Non-string scalars (None, bool, int, float) are emitted as Cypher keywords
    / numerics. Lists become ``[a, b, c]`` array literals.
    """
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(cypher_quote(v) for v in value) + "]"
    if isinstance(value, str):
        # Escape order matters: backslashes first, then single quotes.
        escaped = value.replace("\\", "\\\\").replace("'", "''")
        return f"'{escaped}'"
    raise TypeError(f"cypher_quote: unsupported value type {type(value).__name__}")


# ---------------------------------------------------------------------------
# Agtype wire-format parsing
# ---------------------------------------------------------------------------


# AGE returns agtype values as strings in queries. Common shapes we see:
#   - vertex: '{"id": 844424930131969, "label": "Memory", "properties": {...}}::vertex'
#   - edge:   '{"id": ..., "label": "...", "start_id": ..., "end_id": ..., "properties": {...}}::edge'
#   - scalar: '42', "'hello'", 'true', 'NULL'
#   - list:   '[1, 2, 3]'
#   - object: '{"a": 1}'
#
# The optional ::TYPE suffix is a marker we should strip before JSON-parsing.
_TYPE_SUFFIX_RE = re.compile(r"::(vertex|edge|path|map|node|relationship)$")


@dataclass(frozen=True)
class AgtypeVertex:
    """A Cypher vertex in our normalized form."""

    vertex_id: int
    label: str
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgtypeEdge:
    """A Cypher edge in our normalized form."""

    edge_id: int
    label: str
    start_id: int
    end_id: int
    properties: dict[str, Any] = field(default_factory=dict)


def parse_agtype(raw: str) -> Any:
    """Parse an AGE agtype value into plain Python.

    Returns ``int`` / ``float`` / ``str`` / ``bool`` / ``None`` / ``list`` /
    ``dict`` depending on the wire shape. Returns :class:`AgtypeVertex` or
    :class:`AgtypeEdge` for the typed vertex/edge shapes (we unwrap them so
    callers don't have to deal with the agtype suffix).

    AGE encodes the vertex id as a 48-bit integer (``id = (label_id << 32) |
    local_id``). We return the raw integer — callers needing the
    ``label_id`` part can mask themselves; for traversal we only ever need
    equality / hash on the integer.
    """
    s = raw.strip()
    if not s:
        return None

    # Strip optional ::TYPE suffix that AGE appends to vertex/edge/path values.
    # The suffix appears after each element of a list too, not just at the end.
    # e.g. '[{"id": 1, ...}::vertex, {"id": 2, ...}::vertex]' — strip inside the list.
    s = _strip_agtype_suffix_in_list(s) if s.startswith("[") else _TYPE_SUFFIX_RE.sub("", s)

    # Scalar literals come back as bare tokens. JSON-parsing these would fail.
    upper = s.upper()
    if upper == "NULL":
        return None
    if upper == "TRUE":
        return True
    if upper == "FALSE":
        return False
    if s.startswith("{"):
        # Could be a typed vertex/edge (after ::TYPE stripping) or a plain
        # object. Check for edge first because edges have start_id/end_id
        # which distinguish them from vertices (which only have id/label/
        # properties). Then check for vertex. Otherwise return a plain dict.
        obj = json.loads(s)
        if isinstance(obj, dict) and {"label", "start_id", "end_id"} <= obj.keys():
            return AgtypeEdge(
                edge_id=int(obj["id"]),
                label=str(obj["label"]),
                start_id=int(obj["start_id"]),
                end_id=int(obj["end_id"]),
                properties=dict(obj.get("properties") or {}),
            )
        if isinstance(obj, dict) and "label" in obj and "properties" in obj:
            return AgtypeVertex(
                vertex_id=int(obj["id"]),
                label=str(obj["label"]),
                properties=dict(obj.get("properties") or {}),
            )
        return obj
    if s.startswith("["):
        return json.loads(s)
    if s.startswith("'") and s.endswith("'") and len(s) >= 2:
        # Single-quoted Cypher string. Doubled '' inside is an escaped quote.
        inner = s[1:-1].replace("''", "'")
        return inner
    # Numeric: try int first, fall back to float.
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError as exc:
        raise ValueError(f"parse_agtype: unrecognized literal {s!r}") from exc


def _strip_agtype_suffix_in_list(list_str: str) -> str:
    """Strip ``::vertex`` / ``::edge`` / etc. suffixes inside a list literal.

    ``[a::vertex, b::edge, c]`` → ``[a, b, c]``. Operates by walking the string
    and splitting on top-level commas, then stripping the suffix on each piece.
    """
    assert list_str.startswith("[") and list_str.endswith("]")
    body = list_str[1:-1]
    pieces: list[str] = []
    depth = 0
    in_str: str | None = None
    buf: list[str] = []
    for ch in body:
        if in_str:
            buf.append(ch)
            if ch == in_str and (len(buf) < 2 or buf[-2] != "\\"):
                in_str = None
            continue
        if ch in ('"', "'"):
            in_str = ch
            buf.append(ch)
            continue
        if ch in "{[":
            depth += 1
            buf.append(ch)
            continue
        if ch in "}]":
            depth -= 1
            buf.append(ch)
            continue
        if ch == "," and depth == 0:
            piece = "".join(buf).strip()
            pieces.append(_TYPE_SUFFIX_RE.sub("", piece))
            buf = []
            continue
        buf.append(ch)
    if buf:
        piece = "".join(buf).strip()
        pieces.append(_TYPE_SUFFIX_RE.sub("", piece))
    return "[" + ", ".join(pieces) + "]"


# ---------------------------------------------------------------------------
# Plan: SQL rows → GraphRebuildPlan (vertices + edges + stats)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GraphVertex:
    """A vertex in the rebuild plan. ``properties`` are stored as plain Python
    dict and will be JSON-stringified for Cypher SET clauses at execution time.
    """

    kind: VertexKind
    src_id: int  # the id from the source SQL table
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class GraphEdge:
    """An edge in the rebuild plan. ``src_id``/``dst_id`` are the SQL-table
    ids of the source/destination vertices, NOT the AGE-internal vertex ids
    (those are computed at MERGE time)."""

    label: EdgeLabel
    src_kind: VertexKind
    src_id: int
    dst_kind: VertexKind
    dst_id: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class GraphRebuildPlan:
    vertices: list[GraphVertex]
    edges: list[GraphEdge]
    stats: dict[str, int]


# Regex for word-bounded substring matching. \b doesn't recognize '-' as a
# word boundary in Python's re, so we use lookarounds that anchor on either
# a non-alphanumeric or the string start/end.
def _word_bound(pattern: str) -> re.Pattern[str]:
    return re.compile(rf"(?<![A-Za-z0-9_-]){re.escape(pattern)}(?![A-Za-z0-9_-])", re.IGNORECASE)


# Reference-detection regexes (compiled once at import).
_WIKI_MARKER_RE = re.compile(
    r"wiki://([A-Za-z0-9_-]+)"  # wiki://slug
    r"|\[\[([A-Za-z0-9_-]+)\]\]"  # [[slug]]
)
_SKILL_MARKER_RE = re.compile(r"#([A-Za-z0-9_-]+)")


def _skill_marker_match(content: str, name: str) -> bool:
    return any(m.group(1) == name for m in _SKILL_MARKER_RE.finditer(content))


def _skill_tag_match(tags: list[str], name: str) -> bool:
    return name in tags


def _skill_body_match(content: str, name: str) -> bool:
    """True if the skill name appears as a bare word, OUTSIDE any '#name' marker.

    The marker span is excluded so that a body containing only ``#name`` does
    NOT register as a body match — the marker is a stronger, opt-in signal and
    gets credit via ``_skill_marker_match`` instead. Without this guard,
    ``via`` would always be ``both`` whenever a marker matches.
    """
    # Replace every #name marker span with a placeholder of equal length so
    # subsequent searches see whitespace where the marker was.
    sanitized = _SKILL_MARKER_RE.sub(lambda m: " " * len(m.group(0)), content)
    return bool(_word_bound(name).search(sanitized))


def _wiki_slug_match(content: str, slug: str) -> bool:
    """True if a wiki slug appears as a literal substring, word-bounded."""
    # Same guard as _skill_body_match: strip wiki://slug and [[slug]] spans
    # so a marker-only reference doesn't double-count as a literal match.
    sanitized = _WIKI_MARKER_RE.sub(lambda m: " " * len(m.group(0)), content)
    return bool(_word_bound(slug).search(sanitized))


def _wiki_marker_match(content: str, slug: str) -> bool:
    """True if content contains ``wiki://slug`` or ``[[slug]]`` for this slug."""
    return any((m.group(1) or m.group(2)) == slug for m in _WIKI_MARKER_RE.finditer(content))


def plan_graph_rebuild(
    memories: list[dict[str, Any]],
    wikis: list[dict[str, Any]],
    skills: list[dict[str, Any]],
    session_memories: list[dict[str, Any]],
    *,
    min_shared_tags: int = 2,
) -> GraphRebuildPlan:
    """Compute a rebuild plan from SQL result rows.

    Parameters
    ----------
    memories
        Each row must have keys ``id``, ``category``, ``tags`` (list[str]),
        ``content`` (str, may be empty), and optional ``deleted`` (bool).
        Deleted rows are skipped (treated as not present).
    wikis
        Each row must have ``id``, ``slug``, ``title``.
    skills
        Each row must have ``id``, ``name``.
    session_memories
        Each row must have ``memory_id`` and ``session_id``. Used to derive
        ``CO_OCCURS`` edges.
    min_shared_tags
        Minimum number of shared tags for a ``SHARES_TAG`` edge between two
        memories. Default 2 (per design decision 2026-06-25).
    """
    # Filter deleted memories up front — they're not vertices and not in any
    # pair, so every edge builder below can trust the input.
    live_memories = [m for m in memories if not m.get("deleted")]
    memory_ids = {m["id"] for m in live_memories}

    # --- Vertices ---------------------------------------------------------
    vertices: list[GraphVertex] = []
    for m in live_memories:
        vertices.append(
            GraphVertex(
                kind="Memory",
                src_id=m["id"],
                properties={
                    "id": m["id"],
                    "category": m.get("category"),
                    "created_at": m.get("created_at"),
                },
            )
        )
    for w in wikis:
        vertices.append(
            GraphVertex(
                kind="Wiki",
                src_id=w["id"],
                properties={
                    "id": w["id"],
                    "slug": w["slug"],
                    "title": w["title"],
                },
            )
        )
    for s in skills:
        vertices.append(
            GraphVertex(
                kind="Skill",
                src_id=s["id"],
                properties={"id": s["id"], "name": s["name"]},
            )
        )

    # --- Edges ------------------------------------------------------------
    edges: list[GraphEdge] = []

    # SHARES_TAG (Memory ↔ Memory, dedupe unordered pair via min/max).
    tag_pairs: dict[tuple[int, int], set[str]] = {}
    for i, a in enumerate(live_memories):
        for b in live_memories[i + 1 :]:
            shared = sorted(set(a["tags"]) & set(b["tags"]))
            if len(shared) >= min_shared_tags:
                tag_pairs[(a["id"], b["id"])] = set(shared)
    for (a_id, b_id), shared_tags in tag_pairs.items():
        edges.append(
            GraphEdge(
                label="SHARES_TAG",
                src_kind="Memory",
                src_id=a_id,
                dst_kind="Memory",
                dst_id=b_id,
                properties={"tags": sorted(shared_tags)},
            )
        )

    # CO_OCCURS (Memory ↔ Memory, same session_id). Dedupe via (min,max,session).
    co_pairs: dict[tuple[int, int, str], None] = {}
    sessions: dict[str, list[int]] = {}
    for sm in session_memories:
        if sm["memory_id"] not in memory_ids:
            continue
        sessions.setdefault(sm["session_id"], []).append(sm["memory_id"])
    for session_id, mem_ids in sessions.items():
        uniq_mem_ids: list[int] = sorted(set(mem_ids))
        for i in range(len(uniq_mem_ids)):
            for j in range(i + 1, len(uniq_mem_ids)):
                co_a_id: int = uniq_mem_ids[i]
                co_b_id: int = uniq_mem_ids[j]
                co_pairs[(co_a_id, co_b_id, session_id)] = None
    for a_id, b_id, session_id in co_pairs:
        edges.append(
            GraphEdge(
                label="CO_OCCURS",
                src_kind="Memory",
                src_id=a_id,
                dst_kind="Memory",
                dst_id=b_id,
                properties={"session_id": session_id},
            )
        )

    # REFERENCES_WIKI (Memory → Wiki). Detect literal + marker; dedupe pair.
    wiki_refs: dict[tuple[int, int], set[str]] = {}
    for m in live_memories:
        content = m.get("content", "") or ""
        for w in wikis:
            via: set[str] = set()
            if _wiki_slug_match(content, w["slug"]):
                via.add("literal")
            if _wiki_marker_match(content, w["slug"]):
                via.add("marker")
            if via:
                wiki_refs[(m["id"], w["id"])] = via
    for (mem_id, wiki_id), vias in wiki_refs.items():
        edges.append(
            GraphEdge(
                label="REFERENCES_WIKI",
                src_kind="Memory",
                src_id=mem_id,
                dst_kind="Wiki",
                dst_id=wiki_id,
                properties={"via": "both" if vias == {"literal", "marker"} else next(iter(vias))},
            )
        )

    # USES_SKILL (Memory → Skill). Detect tag + body + marker; dedupe pair.
    skill_refs: dict[tuple[int, int], set[str]] = {}
    for m in live_memories:
        tags = m.get("tags", []) or []
        content = m.get("content", "") or ""
        for s in skills:
            skill_via: set[str] = set()
            if _skill_tag_match(tags, s["name"]):
                skill_via.add("tag")
            if _skill_body_match(content, s["name"]):
                skill_via.add("body")
            if _skill_marker_match(content, s["name"]):
                skill_via.add("marker")
            if skill_via:
                skill_refs[(m["id"], s["id"])] = skill_via
    for (mem_id, skill_id), vias in skill_refs.items():
        edges.append(
            GraphEdge(
                label="USES_SKILL",
                src_kind="Memory",
                src_id=mem_id,
                dst_kind="Skill",
                dst_id=skill_id,
                properties={"via": "both" if len(vias) >= 2 else next(iter(vias))},
            )
        )

    stats = {
        "memory_vertices": sum(1 for v in vertices if v.kind == "Memory"),
        "wiki_vertices": sum(1 for v in vertices if v.kind == "Wiki"),
        "skill_vertices": sum(1 for v in vertices if v.kind == "Skill"),
        "shares_tag_edges": sum(1 for e in edges if e.label == "SHARES_TAG"),
        "co_occurs_edges": sum(1 for e in edges if e.label == "CO_OCCURS"),
        "references_wiki_edges": sum(1 for e in edges if e.label == "REFERENCES_WIKI"),
        "uses_skill_edges": sum(1 for e in edges if e.label == "USES_SKILL"),
    }

    return GraphRebuildPlan(vertices=vertices, edges=edges, stats=stats)
